name = "firebase-auth-example"
compatibility_date = "2024-12-22"
workers_dev = true
main = "index.ts"

tsconfig = "./tsconfig.json"

[vars]
# Please set FIREBASE_AUTH_EMULATOR_HOST environment variable in your wrangler.toml.
# see: https://developers.cloudflare.com/workers/platform/environment-variables/#environment-variables-via-wrangler
#
# Example for wrangler.toml
# [vars]
# FIREBASE_AUTH_EMULATOR_HOST = "localhost:8080"
#
# Override values for `--env production` usage
# [env.production.vars]
# FIREBASE_AUTH_EMULATOR_HOST = ""
FIREBASE_AUTH_EMULATOR_HOST = "127.0.0.1:9099"

# See: https://cloud.google.com/iam/docs/keys-create-delete
SERVICE_ACCOUNT_JSON = '{"type":"service_account","project_id":"project12345","private_key_id":"xxxxxxxxxxxxxxxxx","private_key":"-----BEGIN PRIVATE KEY-----XXXXXX-----END PRIVATE KEY-----\n","client_email":"xxxxx@xxxxxx.iam.gserviceaccount.com","client_id":"xxxxxx","auth_uri":"https://accounts.google.com/o/oauth2/auth","token_uri":"https://oauth2.googleapis.com/token","auth_provider_x509_cert_url":"https://www.googleapis.com/oauth2/v1/certs","client_x509_cert_url":"https://www.googleapis.com/robot/v1/metadata/x509/xxxxx@xxxxxx.iam.gserviceaccount.com"}'

# Setup user account in Emulator UI
EMAIL_ADDRESS = "test@example.com"
PASSWORD = "test1234"

PROJECT_ID = "project12345" # see package.json (for emulator)

# Specify cache key to store and get public jwk.
PUBLIC_JWK_CACHE_KEY = "public-jwk-cache-key"

[[kv_namespaces]]
binding = "PUBLIC_JWK_CACHE_KV"
id = "testingId"
preview_id = "testingId"